export { default as Home } from "../Pages/Home";
export { default as PricingPage } from "../Pages/PricingPage";
export { default as SignUpPage } from "../Pages/SignUpPage";
export { default as Navbar } from "../Components/Navbar";
export { default as GlobalStyles } from "../Styles/GlobalStyles";
export { default as Hero } from "../Components/Hero";
export { default as Footer } from "../Pages/Footer";
export { default as SignPage } from "../Pages/SignPage";
export { default as ScrollTops } from "../Components/ScrollTops";
